# Plik konfiguracyjny dla Yarn.
# Ta linia jest kluczowa dla kompatybilności z Electron/Vite.
# Zmusza Yarn do tworzenia standardowego katalogu node_modules,
# zamiast domyślnego trybu Plug'n'Play (PnP).
nodeLinker: node-modules
